// Only the icons the docs use (keeps the bundle small).
import { registerIcons } from "@station/icons";
import {
  IconAdjustments,
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconAppWindow,
  IconArrowsMove,
  IconBold,
  IconBook,
  IconBrandGithub,
  IconBrush,
  IconCheck,
  IconCircleDashed,
  IconCode,
  IconCopy,
  IconDownload,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFolder,
  IconGridDots,
  IconHistory,
  IconHome,
  IconItalic,
  IconLayoutGrid,
  IconLock,
  IconMoon,
  IconPalette,
  IconPencil,
  IconPhoto,
  IconPlus,
  IconSearch,
  IconSettings,
  IconSquare,
  IconSquareDashed,
  IconStack,
  IconSun,
  IconTrash,
  IconTypography,
  IconUnderline,
  IconZoomIn,
} from "@station/icons/tabler";

registerIcons({
  adjustments: IconAdjustments,
  "align-center": IconAlignCenter,
  "align-left": IconAlignLeft,
  "align-right": IconAlignRight,
  "app-window": IconAppWindow,
  "arrows-move": IconArrowsMove,
  bold: IconBold,
  book: IconBook,
  "brand-github": IconBrandGithub,
  brush: IconBrush,
  check: IconCheck,
  "circle-dashed": IconCircleDashed,
  code: IconCode,
  copy: IconCopy,
  download: IconDownload,
  eye: IconEye,
  "eye-off": IconEyeOff,
  file: IconFile,
  folder: IconFolder,
  "grid-dots": IconGridDots,
  history: IconHistory,
  home: IconHome,
  italic: IconItalic,
  "layout-grid": IconLayoutGrid,
  lock: IconLock,
  moon: IconMoon,
  palette: IconPalette,
  pencil: IconPencil,
  photo: IconPhoto,
  plus: IconPlus,
  search: IconSearch,
  settings: IconSettings,
  square: IconSquare,
  "square-dashed": IconSquareDashed,
  stack: IconStack,
  sun: IconSun,
  trash: IconTrash,
  typography: IconTypography,
  underline: IconUnderline,
  "zoom-in": IconZoomIn,
});
