/** Registers every Station element. For per-component imports use "@station/components/<name>". */
import "./define/icon.ts";
import "./define/kbd.ts";
import "./define/button.ts";
import "./define/icon-button.ts";
import "./define/toggle-button.ts";
import "./define/button-group.ts";
import "./define/toolbar.ts";
import "./define/segmented-control.ts";
import "./define/segment.ts";
import "./define/tooltip.ts";
import "./define/text-field.ts";
import "./define/search-field.ts";
import "./define/textarea.ts";
import "./define/number-field.ts";
import "./define/checkbox.ts";
import "./define/switch.ts";
import "./define/radio-group.ts";
import "./define/radio.ts";
import "./define/slider.ts";
import "./define/range-slider.ts";
import "./define/select.ts";
import "./define/option.ts";
import "./define/combobox.ts";
import "./define/section.ts";
import "./define/property-row.ts";
import "./define/tabs.ts";
import "./define/tab.ts";
import "./define/tab-panel.ts";
import "./define/menu.ts";
import "./define/menu-item.ts";
import "./define/popover.ts";
import "./define/dialog.ts";
import "./define/alert-dialog.ts";
import "./define/toast.ts";
import "./define/toaster.ts";
import "./define/progress.ts";
import "./define/spinner.ts";

export type { IconDefinition } from "@station/icons";
export { getIcon, hasIcon, registerIcons } from "@station/icons";
export * from "./elements.ts";
