// Generates src/generated/scales.css and src/generated/layout.css.
// Run: pnpm --filter @station/tokens generate
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { GRAY_ALPHA, GRAY_LIGHTNESS, STATUS_CHROMA_CURVE, STATUS_LIGHTNESS } from "./palette.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src/generated");
mkdirSync(out, { recursive: true });

const header = "/* Generated by scripts/generate.mjs. Do not edit by hand. */\n";
const steps = [...Array(12).keys()].map((i) => i + 1);
const pct = (n) => `${n}%`;
const ld = (light, dark) => `light-dark(${light}, ${dark})`;

// ---- scales ----
const scales = [];

scales.push("  /* Gray: 12 solid steps. Knobs: --st-gray-hue, --st-gray-chroma. */");
for (const s of steps) {
  const color = (l) => `oklch(${pct(l)} var(--st-gray-chroma) var(--st-gray-hue))`;
  scales.push(
    `  --st-gray-${s}: ${ld(color(GRAY_LIGHTNESS.light[s - 1]), color(GRAY_LIGHTNESS.dark[s - 1]))};`,
  );
}

scales.push("\n  /* Gray alpha: stacks on any surface. Used for hover / pressed / fields. */");
for (const s of steps) {
  const color = (l, a) => `oklch(${pct(l)} var(--st-gray-chroma) var(--st-gray-hue) / ${a})`;
  scales.push(
    `  --st-gray-a${s}: ${ld(color(GRAY_LIGHTNESS.light[11], GRAY_ALPHA.light[s - 1]), color(GRAY_LIGHTNESS.dark[11], GRAY_ALPHA.dark[s - 1]))};`,
  );
}

scales.push(
  "\n  /* Accent: gray lightness + accent hue/chroma. Chroma 0 (default) = monochrome near-black. */",
);
for (const s of steps) {
  const k = STATUS_CHROMA_CURVE[s - 1];
  const color = (l) => `oklch(${pct(l)} calc(var(--st-accent-chroma) * ${k}) var(--st-accent-hue))`;
  scales.push(
    `  --st-accent-${s}: ${ld(color(GRAY_LIGHTNESS.light[s - 1]), color(GRAY_LIGHTNESS.dark[s - 1]))};`,
  );
}

for (const name of ["danger", "warning", "success"]) {
  scales.push(`\n  /* ${name[0].toUpperCase()}${name.slice(1)}. Knob: --st-${name}-hue. */`);
  for (const s of steps) {
    const k = STATUS_CHROMA_CURVE[s - 1];
    const color = (l) => `oklch(${pct(l)} calc(var(--st-status-chroma) * ${k}) var(--st-${name}-hue))`;
    scales.push(
      `  --st-${name}-${s}: ${ld(color(STATUS_LIGHTNESS.light[s - 1]), color(STATUS_LIGHTNESS.dark[s - 1]))};`,
    );
  }
}

writeFileSync(join(out, "scales.css"), `${header}\n:where(:root, [theme]) {\n${scales.join("\n")}\n}\n`);

// ---- layout ----
export const SPACE_STEPS = ["0", "0.5", "1", "1.5", "2", "2.5", "3", "4", "5", "6", "8", "10", "12"];
const token = (v) => `--st-space-${v.replace(".", "-")}`;

const spacingTokens = SPACE_STEPS.map(
  (v) => `  ${token(v)}: calc(var(--st-unit) * ${v} * var(--st-density));`,
).join("\n");

const flex = ":where(st-box, st-row, st-column)";
const padded = ":where(st-box, st-row, st-column, st-surface, st-scroll-area)";
const rules = [];
for (const v of SPACE_STEPS) {
  const t = `var(${token(v)})`;
  rules.push(`${flex}[gap="${v}"] { gap: ${t}; }`);
}
for (const v of SPACE_STEPS) {
  const t = `var(${token(v)})`;
  rules.push(`${padded}[padding="${v}"] { padding: ${t}; }`);
  rules.push(`${padded}[padding-x="${v}"] { padding-inline: ${t}; }`);
  rules.push(`${padded}[padding-y="${v}"] { padding-block: ${t}; }`);
}

writeFileSync(
  join(out, "space.css"),
  `${header}\n:where(:root, [theme], [density]) {\n${spacingTokens}\n}\n\n${rules.join("\n")}\n`,
);

console.log("tokens: generated scales.css, space.css");
