// Generates, from meta/*.meta.ts:
//   custom-elements.json          Custom Elements Manifest (schema 2.1)
//   vscode.html-data.json         VS Code HTML autocomplete
//   types/elements.d.ts           attribute + element interfaces, HTMLElementTagNameMap
//   types/{react,preact,solid,vue,svelte}.d.ts   JSX / template typings
// Run: pnpm --filter @station/components generate
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { elements } from "../meta/index.ts";
import type { AttributeMeta, AttributeType, ElementMeta } from "../meta/types.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const typesDir = join(root, "types");
mkdirSync(typesDir, { recursive: true });

const HEADER = "// Generated by scripts/generate.ts from meta/. Do not edit.\n";
const pascal = (tag: string) =>
  tag
    .split("-")
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join("");
const attrsName = (el: ElementMeta) => `${pascal(el.tag)}Attributes`;
const eventsName = (el: ElementMeta) => `${pascal(el.tag)}Events`;
const elementName = (el: ElementMeta) => `${pascal(el.tag)}Element`;
const doc = (text: string, indent = "  ") => `${indent}/** ${text.replace(/\*\//g, "*\\/")} */\n`;
const key = (name: string) => (/^[a-z_$][\w$]*$/i.test(name) ? name : JSON.stringify(name));

function tsType(type: AttributeType, forAttribute: boolean): string {
  if (type === "string") return "string";
  // biome-ignore lint/suspicious/noTemplateCurlyInString: emits a TS template literal type.
  if (type === "number") return forAttribute ? "number | `${number}`" : "number";
  if (type === "boolean") return "boolean";
  return type.map((v) => JSON.stringify(v)).join(" | ");
}

function attrDefault(a: AttributeMeta) {
  return a.default === undefined ? "" : ` Default: \`${a.default}\`.`;
}

// ---------- elements.d.ts ----------
const common: string[] = [HEADER];
for (const el of elements) {
  common.push(`/** <${el.tag}> — ${el.description} */`);
  common.push(`export interface ${attrsName(el)} {`);
  for (const a of el.attributes) {
    common.push(`${doc(a.description + attrDefault(a))}  ${key(a.name)}?: ${tsType(a.type, true)};`);
  }
  common.push("}\n");

  common.push(`export interface ${eventsName(el)} {`);
  for (const e of el.events ?? []) {
    common.push(`${doc(e.description)}  ${key(e.name)}: ${e.type ?? "Event"};`);
  }
  common.push("}\n");

  common.push(`export interface ${elementName(el)} extends HTMLElement {`);
  for (const a of el.attributes) {
    if (!a.property) continue;
    common.push(
      `${doc(a.description + attrDefault(a))}  ${a.property}: ${tsType(a.type, false)} | undefined;`,
    );
  }
  for (const p of el.properties ?? []) common.push(`${doc(p.description)}  ${p.name}: ${p.type};`);
  for (const m of el.methods ?? []) common.push(`${doc(m.description)}  ${m.name}(): void;`);
  for (const e of el.events ?? []) {
    const t = e.type ?? "Event";
    common.push(
      `  addEventListener(type: ${JSON.stringify(e.name)}, listener: (this: ${elementName(el)}, event: ${t}) => void, options?: boolean | AddEventListenerOptions): void;`,
    );
  }
  if (el.events?.length) {
    common.push(
      "  addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;",
    );
  }
  common.push("}\n");
}
common.push("/** Every Station tag. */");
common.push(`export interface StationElements {`);
for (const el of elements) common.push(`  ${JSON.stringify(el.tag)}: ${elementName(el)};`);
common.push("}\n");
common.push(`export interface StationAttributes {`);
for (const el of elements) common.push(`  ${JSON.stringify(el.tag)}: ${attrsName(el)};`);
common.push("}\n");
common.push(`export interface StationEvents {`);
for (const el of elements) common.push(`  ${JSON.stringify(el.tag)}: ${eventsName(el)};`);
common.push("}\n");
common.push("declare global {\n  interface HTMLElementTagNameMap extends StationElements {}\n}\n");
writeFileSync(join(typesDir, "elements.d.ts"), common.join("\n"));

/** `on<name>` handler props. Native change/input keep framework typing; the rest are lowercase. */
function eventProps(el: ElementMeta, handler: (type: string) => string, skip: string[] = []): string {
  return (el.events ?? [])
    .filter((e) => !skip.includes(e.name))
    .map((e) => `${key(`on${e.name}`)}?: ${handler(e.type ?? "Event")}`)
    .join("; ");
}

function jsxBlock(open: string, close: string, entry: (el: ElementMeta) => string, importLine: string) {
  const lines = [
    HEADER,
    importLine,
    `import type { ${elements.flatMap((el) => [attrsName(el), elementName(el)]).join(", ")} } from "./elements.js";`,
    "",
    open,
  ];
  for (const el of elements) lines.push(`      ${JSON.stringify(el.tag)}: ${entry(el)};`);
  lines.push(close, "", "export {};", "");
  return lines.join("\n");
}

// ---------- React 19 ----------
// React routes onChange / onInput through its own events; other events bind as `on<name>` in lowercase.
writeFileSync(
  join(typesDir, "react.d.ts"),
  jsxBlock(
    'declare module "react" {\n  namespace JSX {\n    interface IntrinsicElements {',
    "    }\n  }\n}",
    (el) =>
      `React.DetailedHTMLProps<Omit<React.HTMLAttributes<${elementName(el)}>, keyof ${attrsName(el)}>, ${elementName(el)}> & ${attrsName(el)} & { class?: string; ${eventProps(el, (t) => `(event: ${t}) => void`, ["change", "input"])} }`,
    'import type * as React from "react";',
  ),
);

// ---------- Preact ----------
writeFileSync(
  join(typesDir, "preact.d.ts"),
  jsxBlock(
    'declare module "preact" {\n  namespace JSX {\n    interface IntrinsicElements {',
    "    }\n  }\n}",
    (el) =>
      `Omit<JSX.HTMLAttributes<${elementName(el)}>, keyof ${attrsName(el)}> & ${attrsName(el)} & { ${eventProps(el, (t) => `(event: ${t}) => void`)} }`,
    'import type { JSX } from "preact";',
  ),
);

// ---------- Solid ----------
writeFileSync(
  join(typesDir, "solid.d.ts"),
  jsxBlock(
    'declare module "solid-js" {\n  namespace JSX {\n    interface IntrinsicElements {',
    "    }\n  }\n}",
    (el) =>
      `Omit<JSX.HTMLAttributes<${elementName(el)}>, keyof ${attrsName(el)}> & ${attrsName(el)} & { ${(
        el.events ?? []
      )
        .map((e) => `${key(`on:${e.name}`)}?: (event: ${e.type ?? "Event"}) => void`)
        .join("; ")} }`,
    'import type { JSX } from "solid-js";',
  ),
);

// ---------- Vue 3 (Volar reads GlobalComponents for templates) ----------
{
  const lines = [
    HEADER,
    'import type { DefineComponent } from "vue";',
    `import type { ${elements.map(attrsName).join(", ")} } from "./elements.js";`,
    "",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emits a TS mapped type.
    "type Handlers<E> = { [K in keyof E as `on${Capitalize<K & string>}`]?: (event: E[K]) => void };",
    "",
    'declare module "vue" {',
    "  interface GlobalComponents {",
  ];
  for (const el of elements) {
    const events = (el.events ?? []).map((e) => `${key(e.name)}: ${e.type ?? "Event"}`).join("; ");
    lines.push(`    ${JSON.stringify(el.tag)}: DefineComponent<${attrsName(el)} & Handlers<{ ${events} }>>;`);
  }
  lines.push("  }", "}", "", "export {};", "");
  writeFileSync(join(typesDir, "vue.d.ts"), lines.join("\n"));
}

// ---------- Svelte 5 ----------
writeFileSync(
  join(typesDir, "svelte.d.ts"),
  jsxBlock(
    'declare module "svelte/elements" {\n  export interface SvelteHTMLElements {\n    ',
    "  }\n}",
    (el) =>
      `Omit<HTMLAttributes<${elementName(el)}>, keyof ${attrsName(el)}> & ${attrsName(el)} & { ${eventProps(el, (t) => `(event: ${t}) => void`, ["change", "input"])} }`,
    'import type { HTMLAttributes } from "svelte/elements";',
  ).replace("SvelteHTMLElements {\n    \n", "SvelteHTMLElements {\n"),
);

// ---------- Custom Elements Manifest ----------
const cemType = (t: AttributeType) => ({ text: tsType(t, false) });
const manifest = {
  schemaVersion: "2.1.0",
  readme: "",
  modules: elements.map((el) => ({
    kind: "javascript-module",
    path: el.module ?? `@station/tokens (${el.tag}, CSS only)`,
    declarations: [
      {
        kind: "class",
        name: el.className ?? pascal(el.tag),
        tagName: el.tag,
        customElement: true,
        description: el.description,
        attributes: el.attributes.map((a) => ({
          name: a.name,
          fieldName: a.property,
          type: cemType(a.type),
          default: a.default === undefined ? undefined : JSON.stringify(a.default),
          description: a.description,
        })),
        members: [
          ...el.attributes
            .filter((a) => a.property)
            .map((a) => ({
              kind: "field",
              name: a.property,
              attribute: a.name,
              type: cemType(a.type),
              description: a.description,
            })),
          ...(el.properties ?? []).map((p) => ({
            kind: "field",
            name: p.name,
            type: { text: p.type },
            description: p.description,
          })),
          ...(el.methods ?? []).map((m) => ({ kind: "method", name: m.name, description: m.description })),
        ],
        events: (el.events ?? []).map((e) => ({
          name: e.name,
          type: { text: e.type ?? "Event" },
          description: e.description,
        })),
        slots: el.slots ?? [],
        cssParts: el.parts ?? [],
        cssProperties: el.cssProperties ?? [],
      },
    ],
    exports: [
      {
        kind: "custom-element-definition",
        name: el.tag,
        declaration: { name: el.className ?? pascal(el.tag) },
      },
    ],
  })),
};
writeFileSync(join(root, "custom-elements.json"), `${JSON.stringify(manifest, null, 2)}\n`);

// ---------- VS Code HTML custom data ----------
const vscode = {
  version: 1.1,
  tags: elements.map((el) => ({
    name: el.tag,
    description: el.description,
    attributes: el.attributes.map((a) => ({
      name: a.name,
      description: a.description + attrDefault(a),
      ...(Array.isArray(a.type) ? { values: a.type.filter(Boolean).map((name) => ({ name })) } : {}),
      ...(a.type === "boolean" ? { valueSet: "v" } : {}),
    })),
  })),
};
writeFileSync(join(root, "vscode.html-data.json"), `${JSON.stringify(vscode, null, 2)}\n`);

console.log(`components: generated typings for ${elements.length} elements`);
